### ISSUE TITLE
Error while connecting to xbox controller driver

### ISSUE THREAD

**Issue by AdamM1985** [csiqueirasilva/PoEController#10]
I started to use this program about a week ago and LOVED IT! I've tried many controller programs and this one is by far the best however it stopped working after windows did an automatic update.

Now every time I try to open poe controller I receive this message "Error while connecting to xbox controller driver. Please ensure that it is correctly connected and configured."

I have spent all day trying to fix this issue and can't figure it out. 

I don't know how to redirect my poe path to the C drive (I read about this in the issue forum).

If anyone knows how to fix it could you please let me know?

**Comment by csiqueirasilva** [comment]
Hello. Thanks for your message!


If it was working in the previous week and you have not made any changes to the location of the game client, you shouldnt worry about redirecting the files to the C drive. Everything should be working.


Have you tried reinstalling the xbox 360 controller driver, or using an old version? I think this might solve your issue.


And if you could, please, provide more detailed steps as what was installed in the update and how is your game client configured.

**Comment by RapidEU** [comment]
I'm using PS4 Controller and it's asking me for an XBOX controller driver, what am I suppose to do? 

I'm using win 10. should I just install the xbox controller driver even though im using ps4 controller?

**Comment by RapidEU** [comment]
Before connecting my PS4 Controller it says, no controller can be found, but after connecting it gives that same error about an xbox controller driver.

**Comment by csiqueirasilva** [comment]
@RapidEU Hi! Are you using https://github.com/nefarius/ScpToolkit ?

**Comment by RapidEU** [comment]
I didn't, now I installed but it still doesn't seem to work. :(
Here is a picture of the SCPMonitor to show the controller is connected [http://imgur.com/RjsPXuN](url)

I tried installing everything and just the controller itself from that ScpToolkit, yet still PoEController gives
"Error while connecting to xbox controller driver. Please ensure it is correctly connected and configured"

**Comment by flotos** [comment]
I am having the same issue as AdamM1985, the xbox controller works on other games, but on startup it diplays the same error message. Do you think we can revert easily the xbox driver ?

**Comment by csiqueirasilva** [comment]
@RapidEU @flotos do you guys have the settings redirected or on c drive ? It might be something i'm not aware of.

I'm still trying to figure out a better way to keep this project running since GGG just announced that there will be no PC controller support for PoE. The code needs to be moved from Javascript into something more reliable (like c++).

**Comment by wheunis** [comment]
Seems like the problem might be related to your detection (or failure therein) of the HID class.
Currently using XBOX One Controller (PID 02D1).
Launching your app produces error regarding the driver.

Adding the HID PID 02FF to Controller.js (as if it was the controller, just to test basically), the app will launch fine with no errors, but the gamepad produces no results (as expected).
Does seem to hint to me that your HID detection needs some updating.

Just thought I would let you know.

**Comment by csiqueirasilva** [comment]
hello everyone

should have been fixed on latest tag (pre-release).
